services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 2000:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "2001:80"
    environment:
      PMA_HOST: mysql:3306
      PMA_USER: user
      PMA_PASSWORD: 123
      UPLOAD_LIMIT: 64M
      upload_max_filesize: 2500M
